### ISSUE TITLE
Fails to import many XWS files

### ISSUE THREAD

**Issue by stickus** [sheepeatingtaz/xwingoverlayer#1]
I've had a bunch of lists that fail to load in testing.  Not sure why, but they seem to be lists using more modern upgrades compared to the ones I've loaded which work.  Any suggestions?

the XWS file that failed latest is here:

> {
>     "version": "0.3.0",
>     "name": "Kath & Crew",
>     "faction": "scum",
>     "points": 100,
>     "pilots": [
>         {
>             "name": "kathscarlet",
>             "ship": "firespray31",
>             "points": 42,
>             "upgrades": {
>                 "ept": [
>                     "fearlessness"
>                 ],
>                 "crew": [
>                     "tailgunner"
>                 ],
>                 "illicit": [
>                     "inertialdampeners"
>                 ],
>                 "title": [
>                     "slavei"
>                 ],
>                 "mod": [
>                     "longrangescanners"
>                 ]
>             }
>         },
>         {
>             "name": "kavil",
>             "ship": "ywing",
>             "points": 33,
>             "upgrades": {
>                 "turret": [
>                     "dorsalturret"
>                 ],
>                 "samd": [
>                     "unhingedastromech"
>                 ],
>                 "ept": [
>                     "pushthelimit"
>                 ],
>                 "mod": [
>                     "vectoredthrusters"
>                 ]
>             }
>         },
>         {
>             "name": "ndrusuhlak",
>             "ship": "z95headhunter",
>             "points": 25,
>             "upgrades": {
>                 "missile": [
>                     "clustermissiles"
>                 ],
>                 "illicit": [
>                     "glitterstim"
>                 ],
>                 "ept": [
>                     "lonewolf"
>                 ],
>                 "mod": [
>                     "guidancechips"
>                 ]
>             }
>         }
>     ],
>     "vendor": {
>         "voidstate": {
>             "squadron_id": 676258,
>             "link": "http://xwing-builder.co.uk/view/676258/kath-crew",
>             "builder": "Voidstate's Unofficial X-Wing Squadron Builder",
>             "builder_link": "http://xwing-builder.co.uk/build"
>         }
>     }
> }

**Comment by sheepeatingtaz** [comment]
Can you post links to some of the XWS files you're​ having problems with?
Happy to take a look and sort the problems out.

**Comment by sheepeatingtaz** [comment]
Sorry, the email I got didn't have the example in. I'll take a look asap.

**Comment by sheepeatingtaz** [comment]
Schoolboy error (Rebel flyer here!) where the XWS import was only trying to match pilot on name, and sometimes the same pilt name might be for multiple ships or factions.

Also added to post_deploy task to make sure existing factions are updated with XWS data.
