### ISSUE TITLE
Issues reading from at least one other XWS file

### ISSUE THREAD

**Issue by stickus** [sheepeatingtaz/xwingoverlayer#2]
Still getting the issue I had before with "Failed to import XWS file".  Tested with the following file:

`{
    "version": "0.3.0",
    "name": "Biggs, Rex, Thayne, Jess",
    "faction": "rebel",
    "points": 99,
    "description": "Rebel Mini Swarm",
    "pilots": [
        {
            "name": "thanekyrell",
            "ship": "arc170",
            "points": 31,
            "upgrades": {
                "amd": [
                    "m9g8"
                ],
                "crew": [
                    "jynerso"
                ],
                "title": [
                    "allianceoverhaul"
                ]
            }
        },
        {
            "name": "captainrex",
            "ship": "tiefighter",
            "points": 14
        },
        {
            "name": "jesspava",
            "ship": "t70xwing",
            "points": 26,
            "upgrades": {
                "amd": [
                    "r2d6"
                ],
                "mod": [
                    "integratedastromech"
                ],
                "ept": [
                    "adaptability"
                ]
            }
        },
        {
            "name": "biggsdarklighter",
            "ship": "xwing",
            "points": 28,
            "upgrades": {
                "amd": [
                    "r5p9"
                ],
                "mod": [
                    "integratedastromech"
                ]
            }
        }
    ],
    "vendor": {
        "voidstate": {
            "squadron_id": 709191,
            "link": "http://xwing-builder.co.uk/view/709191/biggs-rex-thayne-jess",
            "builder": "Voidstate's Unofficial X-Wing Squadron Builder",
            "builder_link": "http://xwing-builder.co.uk/build"
        }
    }
}`

**Comment by sheepeatingtaz** [comment]
Thanks, I can see the problem with this, and some guidance on what do do to resolve it would be appreciated!

The issue is Adaptability. The same xws is used in xwing-data for 2 separate upgrades (+1 and -1 ps).

I can pick an arbitrary one to use, but that isn't necessarily correct: The player doesn't decide up or down until placement.

I could pick one, and then leave it to the overlay controller to adjust the pilot skill if desired prior to the match starting (already available in the overlay control interface). Is this too much hassle? What do you think?

**Comment by sheepeatingtaz** [comment]
On looking into it further, this might be the only solution at the moment: Adaptability as an Upgrade (despite there being a distinction between + and - in the data) doesn't actually 'grant' a PS skill change (VI, for comparison 'grants' a skill increase of 2).

There's a PR outstanding on xwing-data (https://github.com/guidokessels/xwing-data/issues/81) which I will keep an eye on, but the fix just pushed will at least allow the data to load.

**Comment by stickus** [comment]
I think leaving it up to the overlay controller is ideal, as Adaptability
is used to adjust PS after deployment. That's how I would look at handling
it anyway. :)
