### ISSUE TITLE
wont progress from "coming up next" screen

### ISSUE THREAD

**Issue by Crumfish** [sheepeatingtaz/xwingoverlayer#3]
Hi mate. Ive got a game running (after many hours learning on the fly) but it wont leave the "coming up next" screen. Ive set the start time correctly, hit the start match button. Not sure what else to try. Any ideas?

**Comment by sheepeatingtaz** [comment]
Does the toggle button on the Control page not do it? 

_Sent from my Google Pixel XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
